# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a23f4d2e8033464aa22124444b7cfe971a55949e66de682a512483b153f2306faeddfec282d4e017dd907f4fa57c7aaa68aeb34af57805d294de18738b2fcf44

test:
  secret_key_base: 99c11fa34f2bab090f5fc2a187e6cccc7819b5051cfd94a48ce8862604546f88a265410dce6ce4efdc8493d53450e8c80bd5c0b90e155c4902837ce042ffdf85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
